#!/bin/bash

_get_zlink () {
    local repo_url

    if [[ $UPSTREAM_REPO == "Alirvd" || ! $UPSTREAM_REPO =~ (https?)://github.com/.+/.+ ]]
    then
        repo_url="https://github.com/Alirvd/n"
    else
        repo_url="${UPSTREAM_REPO}"
    fi

    local branch="${UPSTREAM_REPO_BRANCH:-master}"
    echo "${repo_url}/archive/${branch}.zip"
}

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_git() {
    local repo_link="$(_get_zlink)"

    $(_run_python_code "from git import Repo
import sys

repo = Repo.clone_from('$repo_link', '.')

if '${UPSTREAM_REPO_BRANCH}' != 'main':
    repo.git.checkout('${UPSTREAM_REPO_BRANCH:-main}')")
}

_start_bot () {
    local zippath="PPF22.zip"
    echo "⌭ جاري تنزيل اكواد السورس ⌭"
    wget -q "$(_get_zlink)" -O "$zippath"
    echo "⌭ تفريغ البيانات ⌭"
    unzip -qq "$zippath"
    echo "⌭ تـم التفريـغ ⌭"
    echo "⌭ يتم التنظيف ⌭"
    rm -rf "$zippath"
    _run_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "⌭ جـاري بـدء تنصيـب المـجــره ⌭ "
    echo ""
    python3 -m zthon
}

_start_bot
